sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  minio:
    endpoint: http://localhost:9000
    access-key: ztSawi1jKte56EHTwqFy
    secret-key: DfJHIzBmoQbv9Y7sHB7o0GaBRvFHOVMxcZaKaIux
    bucket-name: sky-take-out-images
  shop:
    address: 陕西省西安市西北工业大学长安校区北门
  baidu:
    ak:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    #admin-ttl: 7200000
    admin-ttl: 72000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户端配置
    user-secret-key: nwpu2023
    user-ttl: 72000000000
    user-token-name: authentication
  # 配置微信小程序
  wechat:
    appid: wxc333b83ea538923c
    secret: 5953a25fd424589670e8e120496d0aed